services:
  - type: web
    name: deepface-service
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libgl1 libglib2.0-0
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      gunicorn --workers 1 --timeout 120 --worker-class gevent \
      --max-requests 50 --max-requests-jitter 10 \
      --preload deepface_service:app
    envVars:
      - key: OMP_NUM_THREADS
        value: "1"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: CUDA_VISIBLE_DEVICES
        value: ""
